dist: trusty

language: java
jdk:
  - openjdk8

before_install:
  - chmod +x gradlew

install: true

script: ./gradlew clean build :uploadArchives --refresh-dependencies

notifications:
  email: false